package store

import (
	"database/sql"
	"errors"
	"time"

	"peerloop/internal/models"
)

var ErrBookingNotFound = errors.New("booking not found")
var ErrNotParticipant = errors.New("not a participant in this booking")

type BookingStore struct {
	db *sql.DB
}

func NewBookingStore(db *sql.DB) *BookingStore {
	return &BookingStore{db: db}
}

// Create proposes a new session. It starts in "pending" status until the
// invited peer confirms it. meetLink is generated by the handler (see
// internal/handlers/booking_handlers.go) since it doesn't depend on storage.
func (s *BookingStore) Create(requesterID, peerID int64, skillName string, scheduledAt time.Time, meetLink, notes string) (int64, error) {
	res, err := s.db.Exec(`
		INSERT INTO bookings (requester_id, peer_id, skill_name, scheduled_at, meet_link, status, notes)
		VALUES (?, ?, ?, ?, ?, 'pending', ?)
	`, requesterID, peerID, skillName, scheduledAt, meetLink, notes)
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

const bookingSelectCols = `
	b.id, b.requester_id, b.peer_id, b.skill_name, b.scheduled_at,
	b.meet_link, b.status, b.notes, b.recap, b.created_at,
	ru.id, ru.name, ru.email,
	pu.id, pu.name, pu.email
`

func scanBooking(row interface{ Scan(...any) error }) (models.Booking, error) {
	var b models.Booking
	err := row.Scan(
		&b.ID, &b.RequesterID, &b.PeerID, &b.SkillName, &b.ScheduledAt,
		&b.MeetLink, &b.Status, &b.Notes, &b.Recap, &b.CreatedAt,
		&b.Requester.ID, &b.Requester.Name, &b.Requester.Email,
		&b.Peer.ID, &b.Peer.Name, &b.Peer.Email,
	)
	return b, err
}

// Get fetches a single booking by ID, with both participants' basic info populated.
func (s *BookingStore) Get(id int64) (models.Booking, error) {
	row := s.db.QueryRow(`
		SELECT `+bookingSelectCols+`
		FROM bookings b
		JOIN users ru ON ru.id = b.requester_id
		JOIN users pu ON pu.id = b.peer_id
		WHERE b.id = ?
	`, id)
	b, err := scanBooking(row)
	if errors.Is(err, sql.ErrNoRows) {
		return b, ErrBookingNotFound
	}
	return b, err
}

// ForUser returns every booking userID is a participant in, upcoming first.
func (s *BookingStore) ForUser(userID int64) ([]models.Booking, error) {
	rows, err := s.db.Query(`
		SELECT `+bookingSelectCols+`
		FROM bookings b
		JOIN users ru ON ru.id = b.requester_id
		JOIN users pu ON pu.id = b.peer_id
		WHERE b.requester_id = ? OR b.peer_id = ?
		ORDER BY b.scheduled_at DESC
	`, userID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []models.Booking
	for rows.Next() {
		b, err := scanBooking(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, b)
	}
	return out, rows.Err()
}

// SetStatus updates a booking's status, but only if userID is a participant.
func (s *BookingStore) SetStatus(id, userID int64, status string) error {
	res, err := s.db.Exec(`
		UPDATE bookings SET status = ?
		WHERE id = ? AND (requester_id = ? OR peer_id = ?)
	`, status, id, userID, userID)
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotParticipant
	}
	return nil
}

// SetRecap stores an AI-generated (or manual) recap for a booking.
func (s *BookingStore) SetRecap(id int64, recap string) error {
	_, err := s.db.Exec(`UPDATE bookings SET recap = ? WHERE id = ?`, recap, id)
	return err
}
